### ISSUE TITLE
Unknown error when I tried to register in Mesto

### ISSUE THREAD

**Issue by rodukov** [terminaate/mesto#4]
**When I clicked register button nothing happened. Is your social network are working now?**

Browser: Mozilla Firefox
Page: https://mesto-termi.vercel.app/#/register
![upload](https://user-images.githubusercontent.com/101352977/210443330-1763f612-0d05-479a-9ee3-d710fe5f6d89.png)

**Comment by terminaate** [comment]
> **When I clicked register button nothing happened. Is your social network are working now?**
> 
> Browser: Mozilla Firefox
> Page: https://mesto-termi.vercel.app/#/register
> ![upload](https://user-images.githubusercontent.com/101352977/210443330-1763f612-0d05-479a-9ee3-d710fe5f6d89.png)
> 

Read README.md
